### ISSUE TITLE
Datalogger model S3-WIFI-ST supported?

### ISSUE THREAD

**Issue by morts1** [jmccrohan/pysolarmanv5#15]
I have had a recent install of a Solis RHI-3K-48ES-5G Hybrid Inverter inverter and the Data logger serial number is not an Integer. The serial number is a Hex string which pysolarmanv5 does not accept.
Is this Datalogger supported?
Many thanks

**Comment by jmccrohan** [comment]
See issue #8.

I'm not aware of any local access facility on the S3-WIFI-ST unfortunately.
