### ISSUE TITLE
Problem installing on RPi Zero W

### ISSUE THREAD

**Issue by usbrit** [jmccrohan/pysolarmanv5#21]
Hi,
I am having issues installing on RPi zero w with Python 3.10 installed.
Here's the error:
```
pizero@xxxxx:~ $  pip install git+https://github.com/jmccrohan/pysolarmanv5.git
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/jmccrohan/pysolarmanv5.git
  Cloning https://github.com/jmccrohan/pysolarmanv5.git to /tmp/pip-req-build-mUk6nk
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-mUk6nk/setup.py", line 3, in <module>
        with open("README.md", "r", encoding="utf-8") as fh:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-mUk6nk/
```
Any help would be appreciated.
Thanks,
David

**Comment by jmccrohan** [comment]
Are you using Python 3.8+ as per the minimum requirements?

Can you show the output of `pip debug`?

**Comment by usbrit** [comment]
Thanks, re checked and although I thought I had upgraded, was still at 3.7
Sorry to trouble you

**Comment by usbrit** [comment]
OK, so install seems to work, but I'm expecting to find a pysolarmanv5 directory in root so that solismod can the dictionary from it. There isn't one, and therefore solismod doesn't appear to communicate with the inverter.
This is what the install and directory list looks like
![image](https://user-images.githubusercontent.com/53425475/191599481-923f6899-1766-4aae-a03b-464f97bea992.png)
Solismod is receiving messages from mqtt, but doesn't change anything on the inverter
![image](https://user-images.githubusercontent.com/53425475/191599717-fef8f46a-8b01-4035-b2a6-007cc96ed2e8.png)

**Comment by usbrit** [comment]
Figured it out, got some registers working, so connection is good!

**Comment by jmccrohan** [comment]
Glad to hear you got it working.

Will close this issue.
