### ISSUE TITLE
no response from register_scan

### ISSUE THREAD

**Issue by JanSchmidt3** [jmccrohan/pysolarmanv5#23]
I enabled verbose output. For some registers the device seems to answer, but register_scan gives no output. What happens and how should I try to debug?

My device is a "SUN600G3-EU-230" with

Firmware version  MW3_15U_5406_1.471

> Scanning input registers
> 
>DEBUG:pysolarmanv5.pysolarmanv5:SENT: a5 17 00 10 45 00 00 b9 0d 2f f7 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 04 75 30 00 01 2b c9 f9 15
>DEBUG:pysolarmanv5.pysolarmanv5:RECD: a5 10 00 10 15 00 0d b9 0d 2f f7 02 01 d8 e2 01 00 c0 01 00 00 b4 c8 aa 63 05 00 3b 15

**Comment by githubDante** [comment]
The Deye inverters respond only to read_holding_registers (function 0x03). Also the registers in the example here are too high. Try in the range(0, 700). Alternatively you can install [the library](https://github.com/githubDante/deye-controller) I've been working on lately  and use the `deye-read` command.
