### ISSUE TITLE
[Question] Is there a way to control inverter output?

### ISSUE THREAD

**Issue by sjchsuj37sjcbt** [jmccrohan/pysolarmanv5#25]
Hi, thanks for your effort in this project!

Say I have a [Deye SUN](https://www.deyeinverter.com/product/microinverter-1/sun13002000g3eu230.html) micro inverter and want to dynamical control the output power, because I only want to deliver as much power as I currently need in my appartment. I have a Shelly 3EM to measure and want to control the inverter. I read about the server on port 8899 and was wondering if it is possible to control the output power.

Thanks in advance!

**Comment by jmccrohan** [comment]
This is a question for DEYE. I don't have any details of what functionality they provide via Modbus unfortunately.
