### ISSUE TITLE
New release on pypi

### ISSUE THREAD

**Issue by danfoster** [jmccrohan/pysolarmanv5#31]
Hi,

Could you upload a new release to pypi? It would be really useful to have the async and the frame checking logic in a release

Cheers!

**Comment by jmccrohan** [comment]
Hi @danfoster,
I was afk for the last week or so. Just back online today. Let me test out #33 for a few days and if all good, I'll push a new release and upload to pypi.
Cheers.

**Comment by jmccrohan** [comment]
@danfoster I've released v2.5.0 and pushed to PyPi. Sorry for the delay!
