### ISSUE TITLE
Intermittent  V5 Frame Errors

### ISSUE THREAD

**Issue by cpsjones** [jmccrohan/pysolarmanv5#32]
I have got pysolarman communications work with Solis Hybdrid Inverter. The issue is that although it starts fine,  after a few scans it gets  [class 'pysolarmanv5.V5FrameError] exceptions. It always works first time and usually gets stuck with the error but sometimes recovers for a short time.
The code re-initialises the 'modem' after failure but this does not help.
Attached are the source code and a log file produced during testing.
N.B. This code works with data acquisition software I have developed myself (via mqtt) but this is irrelevant to the issue.

WHY cant I upload python files directly
[solis_scan.log.txt](https://github.com/jmccrohan/pysolarmanv5/files/11140092/solis_scan.log.txt)
[solis_scan.py.txt](https://github.com/jmccrohan/pysolarmanv5/files/11140102/solis_scan.py.txt)

**Comment by jmccrohan** [comment]
Resolved by #33 which is included in [v2.5.0](https://github.com/jmccrohan/pysolarmanv5/releases/tag/v2.5.0).
