### ISSUE TITLE
write register code 10

### ISSUE THREAD

**Issue by noyax** [jmccrohan/pysolarmanv5#42]
hello, my Sofar Solar HYD 6000 inverter may have certain registers written with "write register" code 10. I don't see it in pysolarmanv5 but does it exist?

Thanks

**Comment by githubDante** [comment]
Code 10 in hex is 16. See the documentation [here](https://pysolarmanv5.readthedocs.io/en/stable/api_reference.html#pysolarmanv5.PySolarmanV5.write_multiple_holding_registers).
